import { Activity, ArrowRight, Check, CheckCircle2, CircleDot, Clock3, FileText, Fingerprint, GitBranch, LoaderCircle, Radar, ShieldCheck, Terminal, Zap } from 'lucide-react';
import { AreaChart, Area, ResponsiveContainer, YAxis, Tooltip } from 'recharts';
import type { Incident, Agent, Topology, NetworkAction } from '../types';

export function Continuity({topology,incident}:{topology:Topology|null;incident:Incident|null}) {
  const services=topology?.nodes.filter(n=>n.critical)??[];
  const online=services.filter(n=>n.operational).length;
  const samples=incident?.samples.length?incident.samples:[{step:0,online:6,risk:0,latency:45},{step:1,online:6,risk:0,latency:45}];
  return <section className="continuity" aria-label="Service continuity"><div className="continuity-main"><div className="continuity-icon"><ShieldCheck size={26}/></div><div><div className="continuity-count"><strong>{topology?online:'–'}<span> / 6</span></strong><span>CRITICAL SERVICES<br/>ONLINE</span></div><p>{incident?.status==='CONTAINED'?'Threat contained. Essential services uninterrupted.':'Continuous protection for the services that matter.'}</p></div></div><div className="service-pills">{services.map(n=><span key={n.id} title={`${n.name}: ${n.state.replace('_',' ')}; ${n.operational?'online':'offline'}`}><i className={n.operational?'status-dot':'status-dot danger'}/>{({hospital:'Hospital',emergency:'Emergency',energy:'Energy grid',traffic_center:'Traffic',safety:'Public safety',control:'City control'} as Record<string,string>)[n.id]}</span>)}</div><div className="availability-chart"><div><span>Service availability</span><strong>{topology?`${Math.round(online/6*100)}%`:'—'}</strong></div><ResponsiveContainer width="100%" height={36}><AreaChart data={samples}><YAxis hide domain={[0,6]}/><Tooltip contentStyle={{background:'#13212b',border:'1px solid #304554',color:'#e6eff5'}} labelFormatter={()=>'Simulated incident event'} formatter={(value)=>[`${value} / 6`,'Online']}/><Area type="stepAfter" dataKey="online" stroke="#7ee5bc" strokeWidth={2} fill="#7ee5bc" fillOpacity={.1} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></section>;
}

export const phases=[['ATTACK','Attack'],['DETECT','Detect'],['CLASSIFY','Classify'],['IMPACT','Predict impact'],['PLAN','Plan response'],['POLICY','Policy check'],['NETWORK','Network response'],['CONTAINED','Contained'],['COMPLETE','Report']];
export function Storyline({incident}:{incident:Incident|null}) {
  const index=incident?phases.findIndex(([id])=>id===(incident.phase==='APPROVAL'?'POLICY':incident.phase)):-1;
  return <div className="storyline" aria-label="Defense progress">{phases.map(([id,label],i)=><div key={id} className={`${i<index?'past':''} ${i===index?'current':''} ${i===0&&incident?'attack-stage':''}`}><span className="step-number">{i<index?<Check size={11}/>:String(i+1).padStart(2,'0')}</span><span>{label}</span>{i<phases.length-1&&<ArrowRight size={12} className="step-arrow"/>}</div>)}</div>;
}

export function ThreatPanel({incident,topology,approve,busy,onReport}:{incident:Incident|null;topology:Topology|null;approve:(d:'APPROVE'|'REJECT')=>unknown;busy:boolean;onReport:()=>void}) {
  const contained=incident?.status==='CONTAINED';
  const risk=incident?.residual_impact?.score??incident?.impact?.score??0;
  const name=(id:string)=>topology?.nodes.find(n=>n.id===id)?.name??id;
  return <section className={`panel threat-panel ${contained?'contained':''}`} aria-label="Incident intelligence"><div className="panel-heading"><div><span className="eyebrow">INCIDENT INTELLIGENCE</span><h2>{contained?'Containment verified':incident?'Active investigation':'Defense standing by'}</h2></div><span className={`pill ${incident&&!contained?'coral':'green'}`}>{contained?'CONTAINED':incident?.status==='AWAITING_APPROVAL'?'APPROVAL':incident?'ACTIVE':'ARMED'}</span></div>
    <div className="threat-content">{!incident?<><div className="ready-radar"><Radar size={54} strokeWidth={1}/><i/></div><h3>Ready to defend.</h3><p>Launch a scenario to follow a threat from first signal to safe containment.</p><div className="standby-list"><span><CheckCircle2 size={15}/>Six agents ready</span><span><CheckCircle2 size={15}/>Service protection policies loaded</span><span><CheckCircle2 size={15}/>Local network simulator connected</span></div></>:<>
      <div className="incident-id"><span>{incident.id}</span><span>{incident.mode==='fast'?'FAST PITCH':'GUIDED'}</span></div>
      <h3>{incident.title}</h3><div className="source-line"><Fingerprint size={16}/>{name(incident.source)}<span className={`pill ${contained?'green':'coral'}`}>{contained?'ISOLATED':'SOURCE'}</span></div>
      <div className="risk-row"><div><span className="eyebrow">{contained?'RESIDUAL RISK':'PROJECTED SERVICE RISK'}</span><div className="risk-value"><strong>{incident.impact?risk:'—'}</strong><span>/ 100</span></div></div><span className={`risk-level ${contained?'green':'coral'}`}>{contained?'CONTAINED':incident.impact?.severity??'ASSESSING'}</span></div><div className="risk-meter"><i style={{width:`${risk}%`}}/></div>
      {incident.classification&&<div className="mitre-card"><span className="eyebrow">MITRE ATT&CK · {incident.classification.techniques[0].domain}</span>{incident.classification.techniques.map(t=><a href={t.url} target="_blank" rel="noreferrer" key={t.id}><code>{t.id}</code><span>{t.name}</span><ArrowRight size={14}/></a>)}<p>{incident.classification.techniques[0].tactic} · {Math.round(incident.classification.confidence*100)}% rule confidence</p></div>}
      {incident.impact&&<div className="propagation"><span className="eyebrow"><GitBranch size={13}/>PROJECTED PROPAGATION</span><p>{incident.impact.propagation_path.map(name).join(' → ')}</p></div>}
      {incident.status==='AWAITING_APPROVAL'&&<div className="approval-card" role="alert"><h4><ShieldCheck size={18}/>Operator decision required</h4><p>Isolate the shared edge segment after protecting service routes. Reject to use endpoint-only containment.</p>{incident.auto_approve&&<span className="auto-label">Demo auto-approval enabled · simulated operator</span>}<div><button className="button primary small" disabled={busy||!!incident.approvals.length} onClick={()=>approve('APPROVE')}>Approve</button><button className="button small" disabled={busy||!!incident.approvals.length} onClick={()=>approve('REJECT')}>Reject · safe fallback</button></div></div>}
      {contained&&<div className="containment-message"><ShieldCheck size={21}/><span>Source isolated.<br/><strong>{topology?.nodes.filter(n=>n.critical&&n.operational).length ?? 0} / 6 critical services online.</strong></span></div>}
      {incident.report&&<button className="button report-button" onClick={onReport}><FileText size={16}/>Generate Incident Report<ArrowRight size={16}/></button>}
      {incident.status==='FAILED'&&<p role="alert" className="error-copy">{incident.outcome}</p>}
      {incident.status==='INTERRUPTED'&&<p className="error-copy">The backend restarted. Restart the scenario for a clean run.</p>}
    </>}</div>
  </section>;
}

const agentIcons:Record<string,typeof Radar>={Sentinel:Radar,Impact:GitBranch,Response:Zap,Compliance:ShieldCheck,Network:Activity,Report:FileText};
export function AgentPanel({agents}:{agents:Agent[]}) {
  return <section className="agents-section" aria-label="Six coordinated agents"><div className="section-heading"><div><span className="eyebrow">COORDINATED INTELLIGENCE</span><h2>Six agents. One defense.</h2></div><span className="micro-label">Deterministic reasoning · shared incident context</span></div><div className="agent-grid">{agents.map((agent,index)=>{const Icon=agentIcons[agent.name]; const active=['ANALYZING','EXECUTING'].includes(agent.state);return <article key={agent.name} className={`agent-card agent-${agent.state.toLowerCase()}`}><div className="agent-card-top"><span className="agent-icon"><Icon size={19}/></span><span className="agent-number">0{index+1}</span><span className="agent-state">{active?<LoaderCircle size={12} className="spin"/>:agent.state==='COMPLETE'?<Check size={12}/>:<CircleDot size={11}/>} {agent.state}</span></div><h3>{agent.name}<span>Agent</span></h3><p className="agent-role">{agent.role}</p><p className="agent-finding">{agent.finding}</p></article>;})}</div></section>;
}

function ActionItem({action}:{action:NetworkAction}) {
  return <div className="action-item"><span className={`action-status ${action.status.toLowerCase()}`}>{action.status==='COMPLETE'?<Check size={14}/>:<LoaderCircle size={14} className="spin"/>}</span><div><div className="endpoint"><span>POST</span><code>{action.endpoint}</code><small>{action.target.replace('_',' ')}</small></div><p>{action.status==='COMPLETE'?String(action.result.summary):action.rationale}</p></div></div>;
}
export function ActionPanel({incident}:{incident:Incident|null}) {
  return <section className="panel actions-panel"><div className="panel-heading"><div><span className="eyebrow">TELECOM DEFENSE LAYER</span><h2>Network-as-Code actions</h2></div><Terminal size={20}/></div><div className="simulation-label"><span className="sim-square"/>SIMULATED NETWORK-AS-CODE ACTIONS</div><div className="action-list" aria-label="Network actions">{incident?.actions.length?[...incident.actions].reverse().map(action=><ActionItem key={action.id} action={action}/>):<div className="empty-feed"><Terminal size={28}/><p>Network actions will appear here.</p><span>Location verification · SIM swap · QoD · isolation · rerouting</span></div>}</div><div className="feed-footer"><span>{incident?.actions.filter(a=>a.status==='COMPLETE').length??0} actions completed</span><span>Local provider · conceptual endpoints</span></div></section>;
}

export function TimelinePanel({incident}:{incident:Incident|null}) {
  return <section className="panel timeline-panel"><div className="panel-heading"><div><span className="eyebrow">EVIDENCE STREAM</span><h2>Incident timeline</h2></div><span className="pill neutral"><Clock3 size={12}/>{incident?.timeline.length??0} events</span></div><div className="timeline-list" aria-label="Incident timeline">{incident?.timeline.length?[...incident.timeline].reverse().map(event=><div className="timeline-item" key={event.seq}><div className={`timeline-mark ${event.type.includes('CONTAINED')||event.type.includes('GENERATED')?'success':''}`}/><div><div className="event-meta"><span>{event.agent??'SYSTEM'}</span><time>{new Date(event.timestamp).toLocaleTimeString('en-GB',{hour12:false})}</time><code>#{String(event.seq).padStart(2,'0')}</code></div><strong>{event.type.replaceAll('_',' ')}</strong><p>{event.message}</p></div></div>):<div className="empty-feed"><Activity size={28}/><p>Listening for the first signal.</p><span>Every decision and action is recorded in the local incident log.</span></div>}</div><div className="feed-footer"><span>Backend event stream</span><span>Ordered · persisted · replayable</span></div></section>;
}
